Quiz/urls.py
from django.urls import path
from . import views
# create urls here..
urlpatterns = [
    path('', views.index, name='home'),
    path('create_quiz/', views.createQuiz, name='createQuiz'),
    path('quiz/<slug>', views.quizDetails, name="quizDetails"),
    path('quiz/participant/<slug>', views.quizParticipant, name="quizParticipant"),
    path('quiz/<slug>/<id>', views.deleteQuestion, name="quizQuesDelete"),
    path('view/quiz/<slug>', views.overview, name="overview"),
    path('exam/<slug>', views.quiz_participation, name="exam"),
    path('quiz_result/<slug>', views.quiz_result, name="quiz_result"),

]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Account.urls')),
    path('', include('Quiz.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quiz/models.py
from django.db import models
from django.db.models import Count, Sum, Case, When, IntegerField, F
# Create your models here.

from Account.models import CustomUser


class Quiz(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

    def get_participation_summary(self):
        return Result.objects.filter(quiz=self).values('user__email', 'user__first_name', 'user__last_name', 'user__profile_pic').annotate(
            total_questions=Count('question'),
            correct_answers=Sum(
                Case(
                    When(user_choice__is_correct=True, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            wrong_answers=Sum(
                Case(
                    When(user_choice__is_correct=False, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            score=Sum(
                Case(
                    When(user_choice__is_correct=True,
                         then=F('question__points')),
                    default=0,
                    output_field=IntegerField()
                )
            )
        )


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(
        Quiz, related_name="question", on_delete=models.CASCADE)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, null=True, blank=True)
    QUESTION_TYPES = [
        ('single_choice', 'Single Choice'),
        ('image', 'image'),
        ('multiple_choice', 'Multiple Choice'),
        ('matching', 'Matching'),
    ]
    question_type = models.CharField(
        max_length=20, choices=QUESTION_TYPES, default='single_choice')
    points = models.IntegerField(default=1)
    time = models.TimeField(null=True)
    feedback = models.TextField(null=True, blank=True)
    ques_text = models.CharField(max_length=255)

    def __str__(self):
        return self.ques_text


class Choice(models.Model):
    question = models.ForeignKey(
        Question, related_name="choices", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    choice_image = models.ImageField(upload_to="quiz/", null=True, blank=True)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

    class Meta:
        db_table = "choices"


# class Result(models.Model):
#     quiz = models.ForeignKey(Quiz, related_name="quiz",
#                              on_delete=models.CASCADE)
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     user_choice = models.ForeignKey(
#         Choice, related_name="result_choice", on_delete=models.CASCADE)
#     # You can add more fields to store user information or timestamps if needed

#     def __str__(self):
#         return f"{self.quiz.name} - {self.user.email}"

#     class Meta:
#         unique_together = ('quiz', 'user')


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, related_name="quiz",
                             on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_choice = models.ForeignKey(
        Choice, related_name="result_choice", on_delete=models.CASCADE)
    feedback = models.TextField(null=True, blank=True)  # Add feedback field

    def __str__(self):
        return f"{self.quiz.name} - {self.user.email}"

Quiz/forms.py
from django import forms
from .models import Question, Choice
from django.forms import inlineformset_factory, modelformset_factory


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['ques_text', 'question_type', 'points', 'topic', 'feedback',]
        widgets = {
            'ques_text': forms.TextInput(attrs={'class': 'input-box', 'placeholder': 'Question name'}),
            'points': forms.NumberInput(attrs={'class': 'input-box'}),
            'question_type': forms.Select(attrs={'class': 'input-box'}),
            'topic': forms.Select(attrs={'class': 'input-box'}),
            'feedback': forms.TextInput(
                attrs={'placeholder': 'Write Feedback'}),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', 'is_correct', 'choice_image']
        widgets = {
            'choice_text': forms.TextInput(attrs={'placeholder': 'Option name', 'class': 'choice_text formset-field'}),
            'choice_image': forms.FileInput(attrs={'class': 'formset-field'}),
            'is_correct': forms.CheckboxInput(attrs={'class': 'checkbox formset-field'}),
        }

Quiz/views.py
from django.http import JsonResponse
from django.utils import timezone
import uuid
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.urls import reverse
from .models import *
from .forms import *
from django.db import transaction, IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Q
from django.contrib import messages
from django.core.paginator import Paginator
from .utils import send_custom_email
# Create your views here.


@login_required
def index(request):
    user = Result.objects.filter(user=request.user)
    result_quiz = user.values('quiz__id')
    quiz = Quiz.objects.all().exclude(id__in=result_quiz)
    return render(request, 'index.html', context={'quiz': quiz})


@login_required
def createQuiz(request):
    if request.POST:
        name = request.POST.get('quiz_name')
        description = request.POST.get('quiz_description')
        quiz = Quiz.objects.create(name=name, description=description)
        title = quiz.name
        quiz.slug = title.replace(' ', '-') + '-' + str(uuid.uuid1())
        quiz.save()
        return HttpResponseRedirect(reverse('quizDetails', kwargs={'slug': quiz.slug}))
    return render(request, 'quiz.html')


@login_required
def quizDetails(request, slug):
    quiz = Quiz.objects.get(slug=slug)
    all_question = Question.objects.filter(quiz=quiz.id)
    ChoiceFormSet = modelformset_factory(Choice, form=ChoiceForm)
    question_form = QuestionForm(request.POST or None)
    formset = ChoiceFormSet(request.POST or None, request.FILES or None,
                            queryset=Choice.objects.none(), prefix='marks')
    if request.method == 'POST':
        # QUESION FORM SAVE
        if question_form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    question = question_form.save(commit=False)
                    question.quiz = quiz
                    question.save()
                    for choice in formset:
                        data = choice.save(commit=False,)
                        data.question = question
                        data.save()

            except IntegrityError:
                print("Error Encountered")
            return HttpResponseRedirect(reverse('quizDetails', kwargs={'slug': quiz.slug}))
        else:
            messages.warning(request, "Something Wrong")
    return render(request, 'quiz_details.html', context={'quiz': quiz, 'question': question_form, 'formset': formset, 'allquestion': all_question})

# Delete quiz question


@login_required
def deleteQuestion(request, slug, id):
    quiz = Quiz.objects.get(slug=slug)
    question = Question.objects.filter(quiz=quiz, id=id)
    question.delete()
    messages.success(request, "Question delete succesfully")
    return HttpResponseRedirect(reverse('quizDetails', kwargs={'slug': slug}))


# @login_required
def takeExam(request, slug):
    quiz = Quiz.objects.get(slug=slug)
    all_question = Question.objects.filter(quiz=quiz.id)
    if request.method == 'POST':
        quiz = get_object_or_404(Quiz, slug=slug)
        total_questions = quiz.question.count()
        user_responses = []
        for question in quiz.question.all():
            user_choice_id = request.POST.get(f"question_{question.id}")
            if user_choice_id:
                user_choice = get_object_or_404(Choice, pk=user_choice_id)
                result = Result.objects.filter(
                    quiz=quiz, user=request.user, question=question).exists()
                if result:
                    messages.success(request, "Your Alreay attend exam")
                    return render(request, 'exam.html', context={'quiz': quiz, 'allquestion': all_question})
                else:
                    Result.objects.update_or_create(
                        quiz=quiz, user=request.user, question=question, user_choice=user_choice, defaults=None)

        # Save user responses to the database
        # for response in user_responses:
        #     try:
        #         response.save()
        #     except Exception as e:
        #         print(e)

        return HttpResponseRedirect(reverse('quiz_result', kwargs={'slug': quiz.slug}))

    return render(request, 'exam.html', context={'quiz': quiz, 'allquestion': all_question})


@login_required
def quiz_participation(request, slug):
    quiz = Quiz.objects.get(slug=slug)

    # Check if the user has already attended the quiz
    existing_results = Result.objects.filter(
        quiz=quiz, user=request.user).first()
    if existing_results:
        # You can redirect them to a page that informs them they've already attended
        return render(request, 'already_attended.html', {'quiz': quiz})

    questions = Question.objects.filter(quiz=quiz)

    if request.method == 'POST':
        for question in questions:
            # Get the selected choices (multiple can be selected)
            choice_ids = request.POST.getlist(f'question_{question.id}_choice')
            feedback = request.POST.get(f'question_{question.id}_feedback')
            print(choice_ids)

            for choice_id in choice_ids:
                user_choice = Choice.objects.get(pk=choice_id)
                Result.objects.create(
                    quiz=quiz, user=request.user, question=question, user_choice=user_choice, feedback=feedback)

        return HttpResponseRedirect(reverse('quiz_result', kwargs={'slug': quiz.slug}))

    return render(request, 'participation.html', {'quiz': quiz, 'questions': questions})


# @login_required
# def quiz_result(request, slug):
    # Get the quiz object based on the quiz_id
    quiz = Quiz.objects.get(slug=slug)
    ques = Question.objects.filter(quiz=quiz)

    # Get the user's results for the quiz
    user_results = Result.objects.filter(quiz=quiz, user=request.user)
    correct_answer = user_results.filter(user_choice__is_correct=True)
    answered_question_ids = user_results.values_list('question_id', flat=True)
    unanswered_questions = Question.objects.filter(
        quiz=quiz).exclude(id__in=answered_question_ids)

    score = sum([x['question__points'] for x in correct_answer.values(
        'question__points')])
    total_correct = correct_answer.count()
    total_wrong = user_results.filter(user_choice__is_correct=False).count()

    context = {
        'quiz': quiz,
        'total_correct': total_correct,
        'total_wrong': total_wrong,
        'score': score,
        'unanswered_questions': unanswered_questions,
        'user_results': user_results,
    }
    template_path = 'email_template.html'
    subject = quiz.name
    recipient_list = [request.user.email]
    try:
        send_custom_email(subject, recipient_list, template_path, context)
        messages.success(request, "Your Result Published.Check Your Mail.")
    except Exception as e:
        messages.warning(request, "Sorry ,we can't send mail.")
        print(e)
    return render(request, 'quiz_result.html', context)


@login_required
def quiz_result(request, slug):
    quiz = Quiz.objects.get(slug=slug)
    user = request.user

    # Get the user's results for the quiz
    user_results = Result.objects.filter(quiz=quiz, user=user)
    answered_question_ids = user_results.values_list('question_id', flat=True)
    unanswered_questions = Question.objects.filter(
        quiz=quiz).exclude(id__in=answered_question_ids)

    context = {
        'quiz': quiz,
        'user_results': user_results,
        'unanswered_questions': unanswered_questions,
    }

    # Count the number of correct answers and calculate the score
    total_correct = 0
    score = 0

    for result in user_results:
        correct_answers = result.question.choices.filter(is_correct=True)
        user_choices = [result.user_choice]
        print(correct_answers)
        print(user_choices)
        # Check if the user's choices match the correct answers
        if set(correct_answers) == set(user_choices):
            total_correct += 1
            score += result.question.points

    total_wrong = user_results.count() - total_correct

    context['total_correct'] = total_correct
    context['total_wrong'] = total_wrong
    context['score'] = score

    template_path = 'email_template.html'
    subject = quiz.name
    recipient_list = [request.user.email]
    try:
        send_custom_email(subject, recipient_list, template_path, context)
        messages.success(request, "Your results have been sent to your email.")
    except Exception as e:
        messages.warning(request, "Sorry, we couldn't send the email.")
        print(e)

    return render(request, 'quiz_result.html', context)


@login_required
def overview(request, slug):
    quiz = Quiz.objects.get(slug=slug)
    quiz_point = Question.objects.filter(
        quiz=quiz.id).aggregate(total=Sum('points'))['total']
    return render(request, 'overview.html', context={'quiz': quiz, 'points': quiz_point})


@login_required
def quizParticipant(request, slug):
    quiz = Quiz.objects.get(slug=slug)
    quiz_point = Question.objects.filter(
        quiz=quiz.id).aggregate(total=Sum('points'))['total']
    paricipant = quiz.get_participation_summary()
    print(paricipant)

    return render(request, 'participant.html', context={'user_results': paricipant, 'quiz': quiz, 'points': quiz_point})

Quiz/templates/already_attended.html
<!DOCTYPE html>
<html>

<head>
    <title>Quiz Already Attended</title>
</head>

<body>
    <h1>You have already attended this quiz.</h1>
    <p>You cannot attend the same quiz multiple times.</p>
</body>

</html>

Quiz/templates/index.html
{% extends "base.html" %} {% block style%}
<style>
  .all-quiz {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    margin: 50px 50px;
    grid-column-gap: 20px;
    grid-row-gap: 40px;
  }
</style>
{% endblock %} {% block body %} {% load static%} {% load custom_filters %}
<div class="all-quiz">
  {% if quiz %}
  {% for quiz in quiz %}
  <div class="card">
    <div class="card-body">
      <img width="100%" height="140px" style="border-radius: 8px; object-fit: cover" alt="" loading="lazy"
        src="{% static 'asset/card-image.jpg'%}" />
      <h2>{{quiz.name}}</h2>
    </div>
    <div class="card-footer">
      <div class="user-action-count">
        <div class="like-dislike-count">
          <span>{{quiz.question.count}} Question</span>
          <span>•</span>
          <span>{{quiz.question.count|mul:1}} points</span>
        </div>
        <div class="like-dislike-count">
          <span>Time: {{quiz.question.count|toTime:75}}</span>
          <span>•</span>
          <span>last date</span>
        </div>
      </div>
      <div class="user-action">
        <a class="button button-light" href="{% url 'overview' quiz.slug %}">
          overview
        </a>
        {% if user.is_superuser %}
        <a class="button button-light" href="{% url 'quizParticipant' quiz.slug %}">
          Participant
        </a>
        <a class="button" href="{% url 'quizDetails' quiz.slug %}"> Edit </a>
        {% else %}
        <a class="button" onclick="return confirm('Are You sure ?');" href="{% url 'exam' quiz.slug %}">
          Take exam
        </a>
        {% endif %}
      </div>
    </div>
  </div>


  {% empty %}
  <h1>No Data Found</h1>
  {% endfor %}
  {% else %}
  <h1>No Data Found</h1>
  {% endif %}
</div>
{% endblock body %}

Quiz/templates/overview.html
{% extends "base.html" %} {% load static %} {% block style %}
{% load custom_filters %}
<style>
    .quiz-container {
        padding: 20px 10px;
        background: white;
        margin-bottom: 10px;
        border-radius: 4px;
    }

    .quiz-box {
        padding: 10px;
        background-color: white;
        border-radius: 4px;
    }

    .question {
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-bottom: 1px solid #dedede;
    }

    .right-item {
        display: flex;
        gap: 4px;
        justify-content: flex-end;
    }

    input#id_points {
        width: 25px;
    }

    select#id_topic {
        width: 45%;
    }

    input#id_feedback {
        padding: 10px;
        border: none;
    }

    .quiz-footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px 0px;
        border-top: 1px solid #dfdfdf;
    }

    .options {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 10px;
    }

    .choice_text {
        padding: 10px 20px;
        border: 1px solid #5d5d5d;
    }

    .add-option {
        padding: 10px;
        margin-left: 23px;
        background: #f9f9f9;
        border-radius: 4px;
        display: inline-block;
        margin-bottom: 30px;
        color: gray;
        border: none;
    }

    .add-option:hover {
        color: #2f41e2;
        cursor: pointer;
    }

    .question-header div {
        display: flex;
        gap: 4px;
        padding-bottom: 10px;
    }

    .list-options {
        display: flex;
        flex-direction: column;
    }

    .option-item {
        display: flex;
        gap: 8px;
        padding: 8px 8px;
        border-radius: 8px;
        margin: 5px 0px;
    }

    .qustion-list {
        background: white;
        padding: 10px;
        margin: 10px 0px;
    }

    .box {
        display: flex;
        justify-content: space-around;
        flex-direction: row;
        gap: 30px;
        margin: 27px 0px;
    }

    .box-item {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background: beige;
        padding: 15px;
        border-radius: 8px;
        width: 100%;
    }
</style>
{% endblock style %} {% block body %}
<div class="container" style="margin: 10px 25%; padding: 15px; border-radius: 4px">
    <div class="quiz-container">
        <h1>{{ quiz.name }}</h1>
        <p>{{quiz.description}}</p>
        <div class="box">
            <div class="box-item" style="background-color: rgb(165 224 165);">
                <h1>{{quiz.question.count}}</h1>
                <p>Total Question</p>
            </div>
            <div class="box-item" style="background-color: rgb(182 184 251);">
                <h1>{{ points }}</h1>
                <p>Points</p>
            </div>
            <div class="box-item" style="background-color: rgb(227, 206, 240)">
                <h1>{{quiz.question.count|toTime:75}}</h1>
                <p>Time</p>
            </div>
        </div>
        </p>
    </div>
    
    <div class="question-container">
        <div class="qustion-list">
            {% if user.is_superuser %}
            <a class="button" href="{% url 'quizDetails' quiz.slug %}"> Edit </a>
            {% else %}
            <a class="button" href="{% url 'exam' quiz.slug %}"> Take exam
            </a>
            {% endif %}
        </div>

    </div>
    {% endblock %}

Quiz/templates/quiz_details.html
{% extends "base.html" %} {% load static %} {% block style %}
<style>
  .quiz-container {
    padding: 20px 10px;
    background: white;
    margin-bottom: 10px;
    border-radius: 4px;
  }

  .quiz-box {
    padding: 10px;
    background-color: white;
    border-radius: 4px;
  }

  .question {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 1px solid #dedede;
  }

  .right-item {
    display: flex;
    gap: 4px;
    justify-content: flex-end;
  }

  input#id_points {
    width: 25px;
  }

  select#id_topic {
    width: 45%;
  }

  input#id_feedback {
    padding: 10px;
    border: none;
  }

  .quiz-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 0px;
    border-top: 1px solid #dfdfdf;
  }

  .options {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin: 10px;
  }

  .choice_text {
    padding: 10px 20px;
    border: 1px solid #5d5d5d;
  }

  .add-option {
    padding: 10px;
    margin-left: 23px;
    background: #f9f9f9;
    border-radius: 4px;
    display: inline-block;
    margin-bottom: 30px;
    color: gray;
    border: none;
  }

  .add-option:hover {
    color: #2f41e2;
    cursor: pointer;
  }

  .question-header div {
    display: flex;
    gap: 4px;
    padding-bottom: 10px;
  }

  .list-options {
    display: flex;
    flex-direction: column;
  }

  .list-options img {
    max-width: 100%;
    max-height: 185px;
    object-fit: contain;
    object-position: left;
  }

  .option-item {
    display: flex;
    gap: 8px;
  }

  .qustion-list {
    background: white;
    padding: 10px;
    margin: 10px 0px;
  }
</style>
{% endblock style %} {% block body %}
<div class="container" style="margin: 10px 25%; padding: 15px; border-radius: 4px">
  <div class="quiz-container">
    <h2>{{quiz.name}}</h2>
  </div>
  <form method="POST" enctype="multipart/form-data">
    <div style="display: flex; justify-content: end; margin-bottom: 4px;"> {{question.question_type}}</div>
    <div class="quiz-box" style="background-color: white">

      {% csrf_token %}
      <div class="question">
        <div class="input-container" style="width: 65%">
          {{question.ques_text}}
          <span class="input-massage">Please valid Data.</span>
        </div>
        <div class="right-item">{{question.points}} {{question.topic}}</div>
      </div>
      <div id="option-container">
        {% for form in formset %}
        <div class="options item">
          <group>
            <div class="left-column">

              {{form.is_correct}} {{form.choice_text}}
              {{form.choice_image}}


            </div>
          </group>
          <div class="right-column">
            <button type="button" style="color: black" class="btn remove-form-row" id="{{ formset.prefix }}">
              &#x2715;
            </button>
          </div>
        </div>
        {% endfor %} {{ formset.management_form }}
      </div>
      <button type="button" id="{{ formset.prefix }}" class="btn add-option add-form-row">
        Add Option
      </button>
      <div class="quiz-footer">
        <div class="left-item">{{question.feedback}}</div>
        <div class="right-item">
          <input class="button" type="submit" value="Save" />
        </div>
      </div>
  </form>
</div>
<!-- All qustion-list -->
<div class="question-container">
  {% for ques in allquestion %}
  <div class="qustion-list">
    <div class="question-header">
      <div style="display: flex; justify-content: space-between">
        <h3>Q {{forloop.counter}} - {{ques.ques_text}}</h3>
        <a onclick="return confirm('Are sure to  delete?');"
          href="{% url 'quizQuesDelete' slug=quiz.slug id=ques.id %}"><span style="color: red">Delete</span></a>
      </div>
      <div>
        <p>Point: {{ques.points}}</p>
        <p>Topic: {{ques.topic}}</p>
      </div>
    </div>
    <div class="list-options">
      {% for choice in ques.choices.all %}
      {% if choice.is_correct %}
      <div class="option-item">
        <input type="{% if ques.question_type == 'multiple_choice' %}checkbox{% else %}radio{% endif %}"
          name="question_{{ ques.id }}_choice" id="choice_{{choice.id}}" value="{{ choice.id }}" checked />
        <label for="choice_{{choice.id}}">{{choice.choice_text}}</label>
      </div>
      {% if choice.choice_image %}
      <img src="/media/{{choice.choice_image}}" alt="">
      {% endif %}
      {% else %}
      <div class="option-item">
        <input type="{% if ques.question_type == 'multiple_choice' %}checkbox{% else %}radio{% endif %}"
          name="question_{{ ques.id }}_choice" id="choice_{{choice.id}}" value="{{ choice.id }}" disabled />
        <label for="choice_{{choice.id}}">{{choice.choice_text}}</label>
      </div>
      {% if choice.choice_image %}
      <img src="/media/{{choice.choice_image}}" alt="">
      {% endif %}
      {% endif %}
      {% endfor %}
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock body %} {% block script %}
<script src="https://code.jquery.com/jquery-3.7.0.min.js"
  integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/formset.js' %}"></script>

<script>
  const questionType = document.getElementById("id_question_type");
  const radios = document.querySelectorAll('.checkbox');
  questionType.addEventListener("change", function () {
    const textFiled = document.querySelectorAll('.choice_text');
    const is_correct = document.querySelectorAll('.checkbox');

    if (questionType.value == "image") {
      textFiled.forEach((element, i) => {
        element.style.display = "none";
      });
    }
    else if (questionType.value == "single_choice") {
      textFiled.forEach((element, i) => {
        element.style.display = "inline-block";
      });

      is_correct.forEach((element, i) => {
        element.setAttribute('type', 'radio');
      });



    }
    else {
      textFiled.forEach((element, i) => {
        element.style.display = "inline-block";
      });
      is_correct.forEach((element, i) => {
        element.setAttribute('type', 'checkbox');
      });
    }
  });
  radios.forEach((radio) => {
    radio.addEventListener('click', function () {
      // When a radio button is clicked, unselect all other radio buttons
      radios.forEach((otherRadio) => {
        if (otherRadio !== radio) {
          otherRadio.checked = false;
        }
      });
    });
  });

</script>
{% endblock script %}

Quiz/templates/quiz_result.html
{% extends "base.html" %} {% load static %} {% block style %}
<style>
    .quiz-container {
        padding: 20px 10px;
        background: white;
        margin-bottom: 10px;
        border-radius: 4px;
    }

    .quiz-box {
        padding: 10px;
        background-color: white;
        border-radius: 4px;
    }

    .question {
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-bottom: 1px solid #dedede;
    }

    .right-item {
        display: flex;
        gap: 4px;
        justify-content: flex-end;
    }

    input#id_points {
        width: 25px;
    }

    select#id_topic {
        width: 45%;
    }

    input#id_feedback {
        padding: 10px;
        border: none;
    }

    .quiz-footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px 0px;
        border-top: 1px solid #dfdfdf;
    }

    .options {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 10px;
    }

    .choice_text {
        padding: 10px 20px;
        border: 1px solid #5d5d5d;
    }

    .add-option {
        padding: 10px;
        margin-left: 23px;
        background: #f9f9f9;
        border-radius: 4px;
        display: inline-block;
        margin-bottom: 30px;
        color: gray;
        border: none;
    }

    .add-option:hover {
        color: #2f41e2;
        cursor: pointer;
    }

    .question-header div {
        display: flex;
        gap: 4px;
        padding-bottom: 10px;
    }

    .list-options {
        display: flex;
        flex-direction: column;
    }

    .option-item {
        display: flex;
        gap: 8px;
        padding: 8px 8px;
        border-radius: 8px;
        margin: 5px 0px;
    }

    .qustion-list {
        background: white;
        padding: 10px;
        margin: 10px 0px;
    }

    .box {
        display: flex;
        justify-content: space-around;
        flex-direction: row;
        gap: 30px;
        margin: 27px 0px;
    }

    .box-item {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background: beige;
        padding: 15px;
        border-radius: 8px;
        width: 100%;
    }
</style>
{% endblock style %} {% block body %}
<div class="container" style="margin: 10px 25%; padding: 15px; border-radius: 4px">
    <div class="quiz-container">
        <h1>Quiz Result - {{ quiz.name }}</h1>
        <div class="box">
            <div class="box-item" style="background-color: rgb(165 224 165);">
                <h1>{{ total_correct }}/{{quiz.question.count}}</h1>
                <p>Correct</p>
            </div>
            <div class="box-item" style="background-color: rgb(232 140 140);">
                <h1>{{ total_wrong }}</h1>
                <p>Wrong</p>
            </div>
            <div class="box-item" style="background-color: rgb(182 184 251);">
                <h1>{{ score }}</h1>
                <p>Score</p>
            </div>
            <div class="box-item" style="background-color: rgb(227, 206, 240)">
                <h1>{{ unanswered_questions.count }}</h1>
                <p>Unanswer</p>
            </div>
        </div>
        </p>
    </div>
    <!-- All qustion[-list -->
    <div class="question-container">
        <div class="qustion-list">
            <h3>Please check your mail to see more details.</h3>
        </div>

    </div>
    {% endblock %}