Account/urls.py
from django.urls import path
from . import views
#create urls here..
app_name = 'account'
urlpatterns =[
    path('login/',views.logInPage,name='login'),
    path('signup/',views.signUpPage,name='signup'),
    path('logout/',views.log_out,name='logout'),
]

Quiz/urls.py
from django.urls import path
from . import views
# create urls here..
urlpatterns = [
    path('', views.index, name='home'),
    path('create_quiz/', views.createQuiz, name='createQuiz'),
    path('quiz/<slug>', views.quizDetails, name="quizDetails"),
    path('quiz/participant/<slug>', views.quizParticipant, name="quizParticipant"),
    path('quiz/<slug>/<id>', views.deleteQuestion, name="quizQuesDelete"),
    path('view/quiz/<slug>', views.overview, name="overview"),
    path('exam/<slug>', views.quiz_participation, name="exam"),
    path('quiz_result/<slug>', views.quiz_result, name="quiz_result"),

]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Account.urls')),
    path('', include('Quiz.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    {% block headlink%}
    <link rel="stylesheet" href="{% static '/css/nevigation.css' %}" />
    <link rel="stylesheet" href="{% static '/css/global.css' %}" />
    {% endblock %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    {% block style %} {% endblock style %}
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'js/toastr.js' %}"></script>
</head>

<body>
    {% include "header.html" %}
    {% if messages %}
    {% for message in messages %}
    <script type=text/javascript>
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-bottom-left",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }

    toastr.{{ message.tags }}('{{ message }}')
    </script>
    {% endfor %}
    {% endif %}
    {% block body %} {% endblock body %}

    {% block script %} {% endblock script %}
    <script>
        function toggleDropdown() {
            var dropdown = document.getElementById("myDropdown");
            dropdown.classList.toggle("show");
        }

        document.addEventListener("click", function (event) {
            var targetElement = event.target; // Clicked element
            var dropdown = document.getElementById("myDropdown");

            var clickedInsideDropdown = dropdown.contains(targetElement);
            var clickedInsideDropdownParent = targetElement.closest(".dropdownarea");

            if (!clickedInsideDropdown && !clickedInsideDropdownParent) {
                dropdown.classList.remove("show");
            }
        });
    </script>
</body>

</html>

templates/header.html
{% load static %}
<div class="header">
  <a class="left-side" href="/">
    <img class="main-logo" alt="" src="{% static '/asset/mainlogo.png' %}" />
  </a>
  <div class="middle">
    <!-- <input class="search-input-box" type="text" placeholder="Search here..." maxlength minlength /> -->
  </div>
  <div class="right-side">
    {% if user.is_superuser %}
    <a href="{% url 'createQuiz' %}" class="button">Create Quiz</a>
    {% endif %}
    <div class="header-icon">
      <span class="material-symbols-rounded"> dark_mode </span>
    </div>
    <div class="header-icon">
      <span class="material-symbols-rounded"> apps </span>
    </div>
    <div class="dropdownarea">
      <div onclick="toggleDropdown()" class="dropbtn profile-image">
        <img class="image-icon" alt=""
          src="{% if user.profile_pic %} /media/{{user.profile_pic}} {% else %} {% static 'asset/placeholderuser.jpeg' %} {% endif %}" />
      </div>
      <!-- Dropdown menu -->
      <div id="myDropdown" class="dropdown-content">
        <div class="dropdown">
          <div class="dropdown-box">
            <div class="dropdown-user">
              <div class="profile-image" style="width: 66px; height: 66px">
                <img style="width: 66px; height: 66px" alt=""
                  src="{% if user.profile_pic %} /media/{{user.profile_pic}} {% else %} {% static 'asset/placeholderuser.jpeg' %} {% endif %}" />
              </div>
              <div class="dropdown-user-text">
                <h2>{{user.first_name|truncatechars:12}}</h2>
                <p>{{user.email}}</p>
              </div>
            </div>
            <a class="button button-light" href="#"> View Profile </a>
          </div>
          <div class="dropdown-menu">
            <a class="dropdown-menu-item" href="#">
              <span class="material-symbols-rounded"> settings </span>

              <p>Setting</p>
            </a>
            <a class="dropdown-menu-item" href="#">
              <span class="material-symbols-rounded"> key </span>

              <p>Chang password</p>
            </a>
            <a class="dropdown-menu-item" href="#">
              <span class="material-symbols-rounded"> qr_code </span>

              <p>Show Barcode</p>
            </a>
          </div>
          <a class="dropdown-logout" href="{% url 'account:logout' %}">
            <p>Log out</p>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>